### PR TITLE
Fix/desktop login screen

### LINKED ISSUE #205: login screen on desktop has overflow issues
### 🐛 Describe the bug

on resizing the window the container sometimes overflow and is not accessible 

https://github.com/user-attachments/assets/57cbfddf-0047-490c-8dc3-9d43faaf6372

### PR DESCRIPTION
**Pull request by HelloSniperMonkey**
## Description

changed scaffold to single child scroll view to account for edge cases where the component shown in screen is bigger than the screen size

Fixes #205 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

checked by running the test on multiple screen sizes through device preview

Please include screenshots below if applicable.

https://github.com/user-attachments/assets/1314216c-3006-4d79-8ba6-386ee4a110c3

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [x] closes #205

### CODE REVIEW

**Comment by mdmohsin7** [comment]
Looks like this PR also includes the changes of other PRs, pls always create a new branch from origin/main

**Comment by HelloSniperMonkey** [comment]
sorry i made a mistake by merging the branch locally which caused other branches to have the commits from my local main branch
i will be more mindful of these mistakes in future

**Comment by mdmohsin7** [comment]
> sorry i made a mistake by merging the branch locally which caused other branches to have the commits from my local main branch i will be more mindful of these mistakes in future

No worries haha

**Review by mdmohsin7 — APPROVED** [review]
lgtm

**Pull request merged**
