### PR TITLE
fixed scaffold with navigation which was causing logout button to vanishing in tablet mode

### LINKED ISSUE #194: Incorrect navigation bar on tab size view
The navigation bar isn't when I resize the app to tab layout

https://github.com/user-attachments/assets/ae9705fe-014d-4d59-97cf-0c5cc2794659

### PR DESCRIPTION
**Pull request by HelloSniperMonkey**
## Description

This PR addresses the issue which appears when the app is being used on tablets or with device width 451 and 800 and on apps with  resizable window size 

* added the logout button when the device width is in the given range 
* linked it logically to the firebase authenticator to logout user when the button is clicked

this fixes the issue when the user is using the app on tablet or at specified resolution and now is able to logout completely without hassle

Fixes #194 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

* tested it on browser , macos and iphone , ipad simulator for various device widths and had no issue on those 

###Please include screenshots below if applicable.

https://github.com/user-attachments/assets/55b3e8f3-3cec-4bea-9c66-144ceeac1e49

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [x] closes #194 
- [x] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by HelloSniperMonkey** [comment]
Can you please review ? @mdmohsin7

**Review by mdmohsin7 — COMMENTED** [review]
I'm not sure how adding a new side menu item fixes the issue. Perhaps it was already fixed but the deployed version (on which I was checking) was old I guess?

**Comment by HelloSniperMonkey** [comment]
well when i checked the source code i saw for tablet width navigation was done with Scaffold With Drawer and it did not have the logout item while for desktop it had scaffold with navigation rail and it did have the logout item so i just copied it and pasted it on the one which did not have it

**Comment by HelloSniperMonkey** [comment]
> I'm not sure how adding a new side menu item fixes the issue. Perhaps it was already fixed but the deployed version (on which I was checking) was old I guess?

no i had the same issue and i forked from the latest version so i don't think it had to do anything with being old 
anyway it was a quick fix

**Review by mdmohsin7 — APPROVED** [review]
lgtm

**Pull request merged**
